db_path = "db.sqlite"

[mqtt]
#host = "localhost"
#host = "192.168.1.9"
#port = 1883
host = "kdubovikov.ml"
port = 8883
topic_name = "weather"
username = "mqttusr"
password = "mqttpass"

[telegram]
token = "*"

[tls]
ca_cert = "./certs/ca.crt"
