name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        default: true
    - name: Install Diesel CLI
      run: |
        sudo apt-get update
        sudo apt-get install --assume-yes libsqlite3-dev
        cargo install diesel_cli --no-default-features --features sqlite
    - name: Build
      run: cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: wheels
        path: target/release/weather_station_bot